spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: task-service
          uri: http://localhost:8081
          predicates:
            - Path=/task/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: "http://localhost:7080/realms/master"
        registration:
          gateway-client:
            provider: keycloak
            client-id: TaskAsync-CC
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
