spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=api/users/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=api/tasks/**
      discovery:
        locator:
          enabled: true  
          lower-case-service-id: true 
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: "http://localhost:7080/realms/master"
        registration:
          gateway-client:
            provider: keycloak
            client-id: TaskAsync-CC
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL}
user-service:
  url: http://user-service

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
