spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL}

info:
  app:
    name: "notification-service"
    description: "TaskAsync notification application"
    version: "1.0.0"
